name: Release
run-name: Release `${{ github.ref_name}}`

on:
  push:
    tags:
      - v*

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      version_tag: ${{ steps.version_tag.outputs.value }}
      build_date: ${{ steps.build_date.outputs.value }}
    steps:
      - name: Format version tag
        shell: bash
        id: version_tag
        run: |
          TAG=${GITHUB_REF#refs/*/}
          echo "value=$TAG" >> $GITHUB_OUTPUT
      - name: Build date
        shell: bash
        id: build_date
        run: echo "value=$(date +%FT%T%z)" >> $GITHUB_OUTPUT

  docker:
    needs:
      - prepare
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ needs.prepare.outputs.version_tag }}
      GIT_HASH: ${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Login to ghcr.io
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Build `mullsocks`
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 #v6.15.0
        with:
          context: .
          push: true
          tags: |
            ghcr.io/vietanhduong/mullsocks:${{ needs.prepare.outputs.version_tag }}
            ghcr.io/vietanhduong/mullsocks:latest
          build-args: |
            VERSION=2025.6
          platforms: linux/amd64,linux/arm64

      - name: Build `mullsocks-proxy`
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 #v6.15.0
        with:
          context: .
          file: Dockerfile.proxy
          push: true
          tags: |
            ghcr.io/vietanhduong/mullsocks-proxy:${{ needs.prepare.outputs.version_tag }}
            ghcr.io/vietanhduong/mullsocks-proxy:latest
          platforms: linux/amd64,linux/arm64

  release:
    runs-on: ubuntu-latest
    needs: [docker]
    permissions:
      contents: write
      id-token: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda
        with:
          prerelease: true
          files: |
            README.md
            LICENSE
            mullsocks.sh
